name: Sync Leetcode
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # Runs daily
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Code
        uses: LeoYulinYuan/leetcode-sync-actions@v1.0.5
        with:
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: "Solutions"  # Organizes all code inside a 'Solutions' folder
